# https://docs.conda.io/en/latest/miniconda.html
# conda install -n base -c conda-forge mamba
# mamba env create -f environment.yml
# conda activate jupyter-hub-env

name: jupyter-hub-env

channels:
- conda-forge
- defaults

dependencies:
- python=3.7
- pip

### git
- git


### jupyter
- jupyter
- jupyterlab
- jupyterhub
- notebook

### Commun datascience
- pandas
- numpy
- scipy
- seaborn
- scikit-learn
- statsmodels
- matplotlib



